env:
  es2020: true
  node: true
extends:
  - eslint:recommended
  - plugin:node/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:eslint-comments/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  warnOnUnsupportedTypeScriptVersion: true
plugins:
  - '@typescript-eslint'
rules:
  'strict': error
  'no-console': warn
  'eol-last': error
  'no-trailing-spaces': error
  'node/no-unsupported-features/es-syntax': off
  '@typescript-eslint/explicit-module-boundary-types': ['error']
  '@typescript-eslint/explicit-function-return-type': ['error']
  'node/no-missing-import':
    - error
    - tryExtensions: ['.ts', '.js', '.json']
